apiVersion: v2
name: app1
description: A Helm chart for App1 Node.js application
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - nodejs
  - express

maintainers:
  - name: Platform Team
    email: platform@yourdomain.com
