apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jenkins-gitops-cluster
  region: us-east-1

managedNodeGroups:
  - name: app-nodegroup
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 2
    maxSize: 6
    volumeSize: 30
    privateNetworking: true
    labels:
      role: application
      environment: production
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/jenkins-gitops-cluster: "owned"
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
